version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123456
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: